### ISSUE TITLE
proposal for `aes_wide` - Transfer to paper-wideplotting repo

### ISSUE THREAD

**Issue by emitanaka** [xuan-liang/ggmatplot#1]
**Problem**: `ggplot2`, or more widely the grammar of graphics, are a little cumbersome when plotting from data that are in "wide" format. The data typically requires wrangling as seen in `df` in (A) to `long` in (B) from the figure below. Sometimes this means that the data is presented in an unnatural state by the standards of tidy data. 

**Proposal**: have an alternate specification that work with wide data format. We can have say the `aes_wide` that allows selection of columns using the tidyselect syntax. A special function, say `col_index` is used to refer to the column index. 

![proposal-image](https://user-images.githubusercontent.com/7620319/122485473-58a70500-d01a-11eb-84bb-51afbc9d9869.png)

**Comment by fhui28** [comment]
This is an excellent issue from Emi. I propose we translate this to the other repository [ingredient-based wide plotting] reserve this repository for the recipe-based ggwideplot which the RA is to focus on.

**Comment by emitanaka** [comment]
Not relevant now for this package and will be implemented in `ggwide`
