### ISSUE TITLE
disable color and fill for boxplot and violin plots

### ISSUE THREAD

**Issue by emitanaka** [xuan-liang/ggmatplot#13]
Hi all, could we remove color and fill specifications for the boxplot and violin plots? The x-axis already contains the information on the color/fill so it becomes redundant (although it is prettier).

``` r
library(ggmatplot)
#> Loading required package: ggplot2
data(SnowGR, package = "mosaicData")
ggmatplot(SnowGR[,3:14], plot_type = "boxplot") 
#> Warning: Removed 7 rows containing non-finite values (stat_boxplot).
```

![](https://i.imgur.com/StHwSIW.png)

<sup>Created on 2022-05-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by emitanaka** [comment]
There's another issue with this in the x-axis that it's ordering it alphabetically instead of column order. Could that be changed as well? The legend shows the correct order.

**Comment by dilinieseimon** [comment]
@emitanaka This has now been fixed.
